'use strict'
module.exports = {
	name: 'Spanish',
	subsets: {
		'female': ["Agueda","Aldonza","Ana","Angelina","Antonia","Barbola","Bartolomeba","Beatriz","Belit"," Bernardina","Berta","Blanca","Bona","Catalina","Clara","Clarencia","Columba","Constanza"," Cristina","Domenga","Eldonza","Elena","Elo","Elvira","Enderquina","Ermengarda","Ermesinda"," Estefania","Eva","Fafila","Fatima","Felipa","Florinda","Francisca","Fronilde","Gelvira","Gotina"," Gracia","Gundisalba","Guntroda","Ildaria","Ines","Isabel","Isabelica","Isabella","Jimena"," Juana","Leonor","Lucia","Luisa","Lupa","Madelena","Mafalda","Mansuara","Maneula","Margarita"," Maria","Marina","Mariana","Marinella","Mayor","Mencia","Paterna","Placia","Sancha","Scemena"," Serena","Taresa","Teoda","Tegrida","Teresa","Toda","Urraca","Velasquita","Victoria","Violante"," Yolande","Ysabel"],
		'male': ["Adulfo","Agustin","Alfonso","Almerique","Alonso","Alvaro","Alvito","Amentario","Ambroz","Amor"," Andres","Angel","Anselmo","Ansuro","Antonio","Aznaro","Arias","Arnao","Auderico","Ballelo"," Baltasar","Bartolome","Beltran","Berenguer","Bernaldino","Blas","Borredan","Castañon","Cino"," Cosme","Cresconio","Cristobal","Damian","Diego","Domingo","Dulcido","Ederoño","Eliseo","Emilio"," Enrique","Ermegildo","Escobar","Esteban","Estevan","Fadrique","Fagildo","Felipe","Fernán"," Fernando","Flazino","Froila","Francisco","García","Garcilaso","Gascon","Gaspar","Gelmiro"," Geraldo","Godesteo","Gombal","Gomesindo","Gómez","Gonsalvo","Gonzalo","Gudesteo","Gunsedal"," Guntrodo","Guter","Hernan","Hernando","Iago","Iñigo","Ignacio","Isaio","Isidro","Jaime"," Jeronimo","Jesus","Jimeno","Joaquin","Jorge","Juan","Julio","Ladron","Lazaro","Leon","Lope","Lorenco"," Lucas","Luis","Lugo","Manuel","Marcos","Martin","Mateo","Melchor","Mendo","Menendo","Mergildo","Miguel"," Munio","Muño","Nicolao","Nuño","Ochoa","Olivar","Ordoño","Osmundo","Osoro","Oveco","Pancho"," Pascual","Pedro","Pelayo","Pepi","Rafael","Raimundo","Ramiro","Ramón","Ranemiro","Rapinato"," Recaredo","Recessvindo","Rodrico","Rodrigo","Ruberte","Rubin","Salamo","Salvadór","Sancho"," Santiago","Sanzo","Sarracino","Sebastian","Sesmiro","Silvestre","Suero","Tadio","Telo"," Teodemiro","Tiago","Timoteo","Tomas","Tome","Vedillo","Vela","Velasco","Vellito","Vermudo","Vidal"," Vimaro","Vincente","Vistruario"]
	}
}

