'use strict'
module.exports = {
	name: 'Thai',
	subsets: {
		'female': ["Abhasra","Achara","Adung","Anchali","Apsara","Ban"," Banjit","Benjakalyani","Boon-mee","Boon-Nam","Busaba","Butri"," Cantana","Catchada","Chaiama","Chalermwan","Chanachai","Chandra"," Chanhira","Chanthara","Chao-fa","Charanya","Chariya","Charoen"," Charoenrasamee","Charunee","Chatmanee","Chatrsuda","Chatumas","Chaveevan"," Chawiwan","Chintana","Chirawan","Choi","Chomechai","Chomesri"," Chomsiri","Chuachan","Chuasiri","Chulaborn","Chumbot","Churai"," Damni","Dao","Dhipyamongko","Dok","Dok-Rak","Duan"," Duang-Prapha","Hansa","Jaidee","Jintana","Kaeo","Kalaya"," Kamala","Kamchana","Kanchana","Kanita","Kannika","Kanya"," Khae","Khun","Khunying","Kimnai","Klip","Kohsoom"," Krijak","Kultilda","Kwaanfah","Kwanjai","Lalana","Lamai"," Lamom","Lek","Lukden","Ma-dee","Mae","Mae-Duna"," Mae-Khao","Mae-Noi","Mae-Pia","Mae-Ying-Thahan","Mai","Malee"," Mali","Malivalaya","Maliwan","Manee","Mani","Manya-Phathon"," Maprang","Mekhala","Mekhalaa","Mekhla","Monthani","Naruemon"," Ngam","Ngor","Nim","Nimnuan","Nittaya","Noi"," Noklek","Noom","Pakpao","Petchra","Phak-Phimonphan","Phan"," Phara","Phi","Phim","Piam","Pichitra","Pitsamai"," Prahong","Pranee","Prang","Praphat","Rajini","Ramphoei"," Ratana","Rochana","Rutana","Saeng","Sangwan","Saowapa"," Sarai","Sarakit","Savitree","Sawat","Simla","Sirikit"," Sirindhorn","Somawadi","Songsuda","Son-Klin","Srinak","Sri-Patana"," Srisuriyothai","Sua","Suchada","Sugunya","Sukanda","Sukonta"," Sumalee","Sumana","Sunanda","Sunatda","Sunetra","Sunisa"," Supaporn","Sureeporn","Talap","Tamarine","Thaksincha","Thao-Ap"," Thiang","Tida","Tookta","Tppiwan","Tui","Tuk"," Tukata","Tulaya","Tum","Tuptim","Ubolratana","Um"," Ung","Wani-Ratana-Kanya","Wipa","Wismita","Yaowalak","Yen"," Ying","Yodmani"],
		'male': ["Alak","Ananda","Annan","Anuia","Anuman","Anurak"," Badinton","Baharn","Bahn","Bapit","Baroma","Bhakdi"," Choonhavon","Bhumipol","Boon-Mee","Boon-Nam","Burimas","Burut","Cha"," Chai","Chairat","Chaiyanuchit","Chaiyo","Chakri","Chalerm"," Chalermchai","Changsai","Chanthara","Chao-Khun-Sa","Chao-Tak","Charoen"," Charoensom","Charong","Chatchalerm","Chatchom","Chatri","Chaturon"," Chavalit","Chesda","Chomanan","","Chompoo","Chongrak","Choochai"," Choonhavan","Chuachai","Chuanchen","Chuia","Chula","Chulalongkorn"," Chulamai","Churai","Chuthamani","Daeng","Darin","Deng"," Dhipyamongkol","Disnadda","Ditaka","Dithakar","Dok","Duchanee"," Emjaroen","Erawan","Fah","Fufanwonich","Gee","Hainad"," Hanuman","Intradit","Ittiporn","Jaidee","Jao","Jarunsuk"," Jatukamramthep","Jayavarman","Kamnan","Kanda","Karmatha","Kasem"," Kasemchai","Kasemsan","Keetau","Khakanang","Khun","Kiet"," Kit","Kitti","Kittibun","Kittichai","Kittichat","Kittikchorn"," Kob","Komalat","Kongsampong","Korn","Kovit","Kraisee"," Kraisingha","Krarayoon","Kriengsak","Kris","Krita","Krom-Luang"," Kukrit","Kusa","Kwanchai","Kwanjai","Lamom","Lamon"," Lap","Leekpie","Leekpai","Lek","Loesan","Luk","Maha"," Mahidol","Malian","Manitho","Mee","Mengrai","Metananda"," Mok","Mokkhavesa","Mongkut","Monyakul","Muoi","Nadee"," Nai-Thim","Nak","Nang-Klao","Narai","Naresuan","Naris"," Narisa","Net","Ngam","Nikom","Nikon","Nintau"," Niran","Nit","Noi","Nongchai","Noppadon","Norachai"," Nuananong","Nui","Nung","Nuta-Laya","Obb","Othong"," Pairat","Paitoon","Pakhdi","Palat","Panyarachun","Paramendr"," Parnchand","Pattama","Pet","Petchara","Petchra","Phaibun"," Phara","Phinihan","Phraisong","Phrom-Borirak","Phya","Pichai"," Pichit","Pira","Pra","Prachuab","Pramoj","Prasong"," Pravat","Praves","Praya","","Pricha","Prisna","Proi"," Pu","Rachotai","Rak","Ramkamhaeng","Rangsan","Ratanankorn"," Ratsami","Sajja","Sanouk","Santichai","Sanun","Sap"," Sarawong","Sarit","Sataheep","Satrud","Sawat","Seni"," Si","Siam","Sinn","Sombat","Somchai","Somdetch"," Somdet-Ong-Yai","Sompron","Son","Songgram","Soo","Sook"," Sophuk","Sri","Srimuang","Su","Suda","Sudarak"," Suk","Sulak","Sum","Sumatra","Sunan","Sundaravej"," Suntarankul","Sunti","Sup","Suphatra","Suphayok","Supoj"," Supp","Supsampantuwongse","Suriwongse","Suriyawong","Sutep","Tai"," Tak-Sin","Tam","Tau","Tep","Tham-Boon","Thammaraja"," Thanarat","Thanit","Thawanya","Thawi","Thongkon","Thurdchai"," Ti","Tiloka","Ting","Tinsulaananda","Tinsulanonda","Ton"," Tong","Totsakan","Toy","Ubol","Udom","Unakan"," Vajiralongkorn","Vajiravudh","Vessandan","Vidura","Wasi","Wattana"," Wiset","Witsanunat","Wongsa","Xuwicha","Yai","Yhukon"," Yindee","Yod","Yongchaiyudh","Yongchaiyuth","Yubamrung"]
	}
}

